- hosts: all
  roles:
    - common

- hosts: all
  roles:
    - nginx
  tags:
    - nginx

- hosts: all
  roles:
    - docker
  tags:
    - docker

- hosts: all
  roles:
    - python
  tags:
    - python

- hosts: all
  roles:
    - snekbox
  tags:
    - snekbox
