- name: Create Snekbox packages directory
  file:
    state: directory
    path: /opt/pythondiscord/snekbox_modules
    mode: '0775'
    owner: root
    group: root
  tags:
    - snekbox::modules

- name: Create the snekbox container
  community.docker.docker_container:
    name: snekbox
    image: ghcr.io/python-discord/snekbox:latest
    privileged: true
    pull: true
    state: started
    mac_address: "ca:fe:ba:be:be:ef"
    recreate: true
    published_ports:
      - "127.0.0.1:3000:8060"
    restart_policy: unless-stopped
    mounts:
      - source: /opt/pythondiscord/snekbox_modules
        target: /snekbox/user_base
        type: bind
    hostname: 'snekbox'

- name: Install snekbox additional modules (run in container)
  community.docker.docker_container_exec:
    container: snekbox
    argv:
      - /bin/sh
      - -c
      - PYTHONUSERBASE=/snekbox/user_base pip install --user {{ modules | join(" ") }}
  tags:
    - snekbox::modules
