tls_email: joe@jb3.dev
tls_well_known_location: /var/www/letsencrypt

sites:
- name: snekbox
  type: reverse-proxy
  domain: snekbox.pydis.com
  upstream: http://localhost:3000
  auth: true

# Pulled from a K:V map of user-hash in Ansible Vault
nginx_basic_auth_creds: "{{ encrypted_nginx_basic_auth_creds }}"
